var hierarchy =
[
    [ "bootloader_t", "structbootloader__t.html", null ],
    [ "canardClass", "classcanardClass.html", null ],
    [ "canardClass::CanardRxQueue", "structcanardClass_1_1CanardRxQueue.html", null ],
    [ "CanParam_t", "structCanParam__t.html", null ],
    [ "configuration_t", "structconfiguration__t.html", null ],
    [ "EEprom", "classEEprom.html", null ],
    [ "EERegister", "classEERegister.html", null ],
    [ "ElaborateDataParam_t", "structElaborateDataParam__t.html", null ],
    [ "canardClass::master::file", "classcanardClass_1_1master_1_1file.html", null ],
    [ "canardClass::flag", "classcanardClass_1_1flag.html", null ],
    [ "Flash", "classFlash.html", null ],
    [ "canardClass::master::heartbeat", "classcanardClass_1_1master_1_1heartbeat.html", null ],
    [ "canardClass::heartbeat_VSC", "unioncanardClass_1_1heartbeat__VSC.html", null ],
    [ "maintenance_t", "structmaintenance__t.html", null ],
    [ "canardClass::master", "classcanardClass_1_1master.html", null ],
    [ "Mppt", "classMppt.html", null ],
    [ "MpptSensorParam_t", "structMpptSensorParam__t.html", null ],
    [ "canardClass::CanardRxQueue::msg", "structcanardClass_1_1CanardRxQueue_1_1msg.html", null ],
    [ "canardClass::next_transfer_id", "classcanardClass_1_1next__transfer__id.html", null ],
    [ "canardClass::port_id", "classcanardClass_1_1port__id.html", null ],
    [ "canardClass::publisher_enabled", "classcanardClass_1_1publisher__enabled.html", null ],
    [ "Flash::QSPI_Info", "structFlash_1_1QSPI__Info.html", null ],
    [ "Flash::QSPI_IT_EventFlag", "unionFlash_1_1QSPI__IT__EventFlag.html", null ],
    [ "report_t", "structreport__t.html", null ],
    [ "sample_t", "structsample__t.html", null ],
    [ "SupervisorParam_t", "structSupervisorParam__t.html", null ],
    [ "system_message_t", "structsystem__message__t.html", null ],
    [ "system_status_t", "structsystem__status__t.html", null ],
    [ "task_t", "structtask__t.html", null ],
    [ "cpp_freertos::Thread", null, [
      [ "CanTask", "classCanTask.html", null ],
      [ "ElaborateDataTask", "classElaborateDataTask.html", null ],
      [ "MpptSensorTask", "classMpptSensorTask.html", null ],
      [ "SupervisorTask", "classSupervisorTask.html", null ],
      [ "WdtTask", "classWdtTask.html", null ]
    ] ],
    [ "canardClass::master::timestamp", "classcanardClass_1_1master_1_1timestamp.html", null ],
    [ "WdtParam_t", "structWdtParam__t.html", null ]
];